############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Docs"
url = "https://docs.fusion-engine.tech/"
weight = 2

[[main]]
name = "Github"
url = "https://github.com/fusionengine-org/fusion-engine"
weight = 3

[[main]]
name = "Discord Server"
url = "https://discord.com/invite/Smg3CK4ZMc"
weight = 4

[[main]]
name = "Blog"
url = "blog/"
weight = 5

[[main]]
name = "About"
url = "about/"
weight = 6

# footer menu
[[footer]]
name = "Home"
url = "/"
weight = 1

[[footer]]
name = "Docs"
url = "https://docs.fusion-engine.tech/"
weight = 2

[[footer]]
name = "Github"
url = "https://github.com/fusionengine-org/fusion-engine"
weight = 3


[[footer]]
name = "PyPi"
url = "https://pypi.org/project/fusion-engine/"
weight = 4

[[footer]]
name = "Discord Server"
url = "https://discord.com/invite/Smg3CK4ZMc"
weight = 5

[[footer]]
name = "Blog"
url = "blog/"
weight = 6

[[footer]]
name = "About"
url = "about/"
weight = 7
